### ISSUE TITLE
tu codigo afecta todas las pociones de tipo splash

### ISSUE THREAD

**Issue by RepliedK** [ClouderIDev/CustomPotion#1]
Problema: El código contiene una comprobación que verifica si un proyectil (splash potion) es del tipo PotionType::STRONG_HEALING(), y si es así, realiza una acción específica para ese tipo de poción. Sin embargo, esta comprobación puede causar problemas porque no está limitada a una poción en particular. Esto significa que cualquier poción que se lance en el juego y sea detectada como una instancia de SplashPotion activará esta acción, incluso si no es una poción de curación fuerte. Esto puede llevar a un comportamiento incorrecto en el juego, ya que no se está discriminando adecuadamente entre los diferentes tipos de poción.

Solución propuesta: Para solucionar este problema y asegurarse de que la acción solo se realice para las pócimas de curación fuerte, se debe verificar si el tipo de poción es realmente PotionType::STRONG_HEALING() antes de realizar la acción. Aquí tienes una versión corregida del fragmento de código relevante:

```php
public function onHit(ProjectileHitBlockEvent $event): void{
    $projectile = $event->getEntity();

    if($projectile instanceof SplashPotion){
        $potionType = $projectile->getPotionType();

        if($potionType !== null && $potionType->equals(PotionType::STRONG_HEALING())){
            $player = $projectile->getOwningEntity();

            if($player instanceof Player){
                $distance = $projectile->getPosition()->distance($player->getPosition());

                if($distance <= 3.5 && $player->isAlive()){
                    $health = $player->getHealth() + 4.3;
                    $player->setHealth($health > $player->getMaxHealth() ? $player->getMaxHealth() : $health);
                }
            }
        }
    }
}

```

**Comment by ClouderIDev** [comment]
The code has already been corrected and now it only works with the strong healing potion and the projectile now comes out correctly and does not cause that problem, thank you for using the plugin and blessings. 😇
